name: test race
on:
  workflow_dispatch:

jobs:
  cd:
    concurrency:
      cancel-in-progress: true
      group: cicd-cd-concurrency-group
    environment: "${{ matrix.config.DEPLOYMENT_ENVIRONMENT }}"
    name: "cd-${{ matrix.config.DEPLOYMENT_ENVIRONMENT }}"
    runs-on: [ubuntu-latest]
    strategy:
      fail-fast: true
      matrix:
        config:
          - APP_VERSION_ENV: "nonprod"
            DEPLOYMENT_ENVIRONMENT: "np"
            DEPLOYMENT_RUNNER: "cd-ubuntu-s-np"
            GOOGLE_GKE_CLUSTER: "***"
            GOOGLE_GKE_PROJECT: "***"
            GOOGLE_SERVICE_ACCOUNT_HARNESS_DELEGATE: "***"
          - APP_VERSION_ENV: "prod"
            DEPLOYMENT_ENVIRONMENT: "prod"
            DEPLOYMENT_RUNNER: "cd-ubuntu-s-prod"
            GOOGLE_GKE_CLUSTER: "***"
            GOOGLE_GKE_PROJECT: "***"
            GOOGLE_SERVICE_ACCOUNT_HARNESS_DELEGATE: "***"
      max-parallel: 1
    steps:
      - env:
          RUNNER_TOOL_CACHE: /opt/hostedtoolcache2
          RUNNER_TOOL_CACHE2: /opt/hostedtoolcache3
        run: |
          set +e
          echo "RUNNER_TOOL_CACHE is ${RUNNER_TOOL_CACHE}"
          echo "RUNNER_TOOL_CACHE2 is ${RUNNER_TOOL_CACHE2}"
