on: push

jobs:
  test_secret:
    strategy:
      matrix:
        number: ["one", "two"]
        color: ["red", "blue"]
        include:
          - day: monday
          - other: other
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo 'Hello world'


