on: push

jobs:
  test_secret:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./setsecret
      - run: cat sample_secret
      - run: echo wolverine
      - run: echo lovely
      - run: echo UltraSecret
      - run: echo Harry
      - run: echo Potter
