on: push

jobs:
  old_secret:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./oldtest
      - run: cat sample_secret
  test_secret:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./setsecret
      - run: cat sample_secret
      - run: echo wolverine
