name: test race
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: [ rentziass ] 
    steps:
      - env:
          RUNNER_TOOL_CACHE: /opt/hostedtoolcache2
          RUNNER_TOOL_CACHE2: /opt/hostedtoolcache3
        run: |
          set +e
          echo "RUNNER_TOOL_CACHE is ${RUNNER_TOOL_CACHE}"
          echo "RUNNER_TOOL_CACHE2 is ${RUNNER_TOOL_CACHE2}"
